app/configs/__init__.py
from flask import Blueprint

bp = Blueprint("configs", __name__)

from app.configs import routes

app/configs/routes.py
from flask import (
    render_template,  # flask function to render a HTML template with elements replaced.
    flash,  # show a message overlay.
    redirect,  # redirect to another page.
    current_app,
    url_for,  # used to interpret endpoints.
)
from flask_login import (  # flask_login module is a module to help manage module
    login_required,  # used to @login_required decorator to indicate a route MUST be logged in before showing.
    current_user,
)
import os, sys

from pathlib import Path

path_file = os.path.dirname(os.path.realpath(__file__))
path_module = Path(path_file)
sys.path.append(f"{path_module}")

from dotenv import load_dotenv

from app.configs.forms import DTConfigForm, DTConfigForm_Submit, DTConfigForm_Update

from app import db

from app.models import (
    User,
    DICOMTransitConfig,
)  # import data base model for User and Post construct.
from app.configs import bp


"""
This file is responsible for ROUTING the VIEW functions. What happens when you look at a page etc?

Any view needs to be defined here. 

"""

import logging

logger = logging.getLogger()
logging.basicConfig(level=logging.INFO)

# from DICOMTransit.LocalDB.schema import CNBP_blueprint
# envvars = CNBP_blueprint.dotenv_variables


@login_required
@bp.route("/settings", methods=["GET", "POST"])
def settings():
    """
    Show all the configurations, most recent order first
    :return:
    """

    # Fetch all configuration by the current users
    # Retrieve from database the row that contain the user name.
    user_current = User.query.filter_by(username=current_user.username).first()
    list_configs = DICOMTransitConfig.query.filter_by(user_id=user_current.id)

    # Needs to add a way to render the configs and click to link to <li><a href="{{ url_for('configs.update_config') }}">Update Config</a> </li>
    configs = list_configs.paginate(1, current_app.config["POSTS_PER_PAGE"], False)

    # Next URL if they exist.
    next_url = (
        url_for("configs.settings", page=configs.next_num) if configs.has_next else None
    )

    # Previous URL if they exist
    prev_url = (
        url_for("configs.settings", page=configs.prev_num) if configs.has_prev else None
    )

    return render_template(
        "config/TConfigIndex.html",
        title="Current Configurations",
        configs=configs.items,
        next_url=next_url,
        prev_url=prev_url,
    )


@bp.route("/create_config", methods=("GET", "POST"))
@login_required
def create_config():
    """
    The Create View
    """

    form = DTConfigForm_Submit()

    if form.validate_on_submit():
        # Fetch all configuration by the current users
        # Retrieve from database the row that contain the user name.
        user_current = User.query.filter_by(username=current_user.username).first()

        # Get the encryption key from the env.
        load_dotenv()

        # setup
        from config import Config

        config = DICOMTransitConfig(
            DevOrthancIP=form.DevOrthancIP.data,
            DevOrthancPassword=form.DevOrthancPassword.data,
            DevOrthancUser=form.DevOrthancUser.data,
            LORISurl=form.LORISurl.data,
            LORISusername=form.LORISusername.data,
            LORISpassword=form.LORISpassword.data,
            timepoint_prefix=form.timepoint_prefix.data,
            institutionID=form.institutionID.data,
            institutionName=form.institutionName.data,
            projectID_dic=form.projectID_dic.data,
            LocalDatabasePath=form.LocalDatabasePath.data,
            LogPath=form.LogPath.data,
            ZipPath=form.ZipPath.data,
            ProdOrthancIP=form.ProdOrthancIP.data,
            ProdOrthancUser=form.ProdOrthancUser.data,
            ProdOrthancPassword=form.ProdOrthancPassword.data,
            user_id=user_current.id,
        )
        db.session.add(config)
        db.session.commit()

        # Notify the issue.
        flash("Your config entry has been successfully written to the database.")
        return redirect(url_for("configs.settings"))

    return render_template(
        "config/TConfigCreate.html", title="Add a DICOMTransit configuration", form=form
    )


@bp.route("/update_config/<config_id>", methods=("GET", "POST"))
@login_required
def update_config(config_id):
    """
    The Update View
    """
    """
    View function where the editing of the actual functions happen.
    :return:
    """
    form = DTConfigForm_Update()
    # Entry ID based on the parameter passed to the page
    entry_data = DICOMTransitConfig.query.filter_by(id=config_id).first()
    if entry_data is None:
        flash("No suitable data found.")
    else:
        form.DevOrthancIP.data = entry_data.DevOrthancIP
        form.DevOrthancPassword.data = entry_data.DevOrthancPassword
        form.DevOrthancUser.data = entry_data.DevOrthancUser
        form.LORISurl.data = entry_data.LORISurl
        form.LORISusername.data = entry_data.LORISusername
        form.LORISpassword.data = entry_data.LORISpassword
        form.timepoint_prefix.data = entry_data.timepoint_prefix
        form.institutionID.data = entry_data.institutionID
        form.institutionName.data = entry_data.institutionName
        form.projectID_dic.data = entry_data.projectID_dic
        form.LocalDatabasePath.data = entry_data.LocalDatabasePath
        form.LogPath.data = entry_data.LogPath
        form.ZipPath.data = entry_data.ZipPath
        form.ProdOrthancIP.data = entry_data.ProdOrthancIP
        form.ProdOrthancUser.data = entry_data.ProdOrthancUser
        form.ProdOrthancPassword.data = entry_data.ProdOrthancPassword
        flash("Your data entry has been successfully loaded from the database.")

        # If past validation, during submission,
        if form.validate_on_submit() and form.update_entry.data:
            # Update.ENTRY model data
            entry_data.DevOrthancIP = form.DevOrthancIP.data
            entry_data.DevOrthancPassword = form.DevOrthancPassword.data
            entry_data.DevOrthancUser = form.DevOrthancUser.data
            entry_data.LORISurl = form.LORISurl.data
            entry_data.LORISusername = form.LORISusername.data
            entry_data.LORISpassword = form.LORISpassword.data
            entry_data.timepoint_prefix = form.timepoint_prefix.data
            entry_data.institutionID = form.institutionID.data
            entry_data.institutionName = form.institutionName.data
            entry_data.projectID_dic = form.projectID_dic.data
            entry_data.LocalDatabasePath = form.LocalDatabasePath.data
            entry_data.LogPath = form.LogPath.data
            entry_data.ZipPath = form.ZipPath.data
            entry_data.ProdOrthancIP = form.ProdOrthancIP.data
            entry_data.ProdOrthancUser = form.ProdOrthancUser.data
            entry_data.ProdOrthancPassword = form.ProdOrthancPassword.data
            db.session.commit()

            # Notify the issue.
            flash("Your data entry has been successfully written to the database.")
        elif form.delete_entry.data:
            # Notify the issue.
            flash(f"Deleting this entry {config_id}")
            db.session.delete(entry_data)
            db.commit()
            flash(f"Config {config_id} was removed from the database.")

    # Post > Redirect > Get pattern.
    return render_template("config/TConfigView.html", form=form)

app/entries/__init__.py
from flask import Blueprint

bp = Blueprint("entries", __name__)

from app.entries import routes

app/entries/routes.py
from datetime import datetime
from flask import (
    render_template,  # flask function to render a HTML template with elements replaced.
    flash,  # show a message overlay.
    redirect,  # redirect to another page.
    url_for,  # used to interpret endpoints.
)
from flask_login import (  # flask_login module is a module to help manage module
    login_required,  # used to @login_required decorator to indicate a route MUST be logged in before showing.
    current_user,
)

from app.entries.forms import (
    NeonatalDataForm_Submit,
    NeonatalDataForm_Update,
    RequestEntryForm,
)

from app import db

from app.models import (
    Entry,
    User,
)  # import data base model for User and Post construct.
from app.entries import bp


"""
This file is responsible for ROUTING the VIEW functions. What happens when you look at a page etc?

Any view needs to be defined here. 

"""

import logging

logger = logging.getLogger()
logging.basicConfig(level=logging.INFO)


@login_required
@bp.route("/data_entry/", methods=["GET", "POST"])
def data_entry():
    """
    View function where the editing of the actual functions happen.
    :return:
    """
    # Instantiate the form
    form = NeonatalDataForm_Submit()
    form.submit_entry.render_kw = {"enabled": ""}
    # If past validation, during submission,
    if form.validate_on_submit():

        # Retrieve from database the row that contain the user name.
        user_current = User.query.filter_by(
            username=current_user.username
        ).first_or_404()

        # Create the ENTRY model data
        entry = Entry(
            MRN=form.MRN.data,
            CNBPID=form.CNBPID.data,
            birth_weight=form.birth_weight.data,
            birth_date=form.birth_date.data,
            birth_time=form.birth_time.data,
            mri_date=form.mri_date.data,
            mri_reason=str(form.mri_reason.data),
            mri_dx=str(form.mri_diagoses.data),
            dicharge_diagoses=str(form.dicharge_diagoses.data),
            mri_age=form.mri_age.data,
            user_id=user_current.id,
        )
        db.session.add(entry)
        db.session.commit()

        # Notify the issue.
        flash("Your data entry has been successfully written to the database.")
        return redirect(url_for("entries.data_request"))

    return render_template(
        "entries/TEntryCreate.html", title="Add a Data Entry", form=form
    )


@login_required
@bp.route("/data_request/", methods=["POST", "GET"])
def data_request():
    """
    The place to place a request to view data ENTRY form. 
    :return:
    """
    form = RequestEntryForm(current_user.username)
    if form.validate_on_submit():
        id_form = int(form.id.data)
        logger.info(id_form)
        logger.info("Reached here!")
        flash(f"Requesting entry data from ID={str(id_form)}.")
        return redirect(url_for("entries.data_view", id_entry=id_form))
    return render_template(
        "entries/TEntryView.html", title="Load a Data Entry", form=form
    )


@login_required
@bp.route("/data_view/<id_entry>", methods=["GET", "POST"])
def data_view(id_entry):
    """
    View function where the editing of the actual functions happen.
    :return:
    """
    form = NeonatalDataForm_Update()
    # Entry ID based on the parameter passed to the page
    entry_data = Entry.query.filter_by(id=id_entry).first()
    if entry_data is None:
        flash("No suitable data found.")
    else:
        form = NeonatalDataForm_Update()
        form.MRN.data = entry_data.MRN
        form.CNBPID.data = entry_data.CNBPID
        form.birth_weight.data = entry_data.birth_weight
        form.birth_date.data = entry_data.birth_date
        form.birth_time.data = entry_data.birth_time
        form.mri_date.data = entry_data.mri_date
        form.mri_reason.data = entry_data.mri_reason
        form.mri_age.data = entry_data.mri_age
        # form.submit.render_kw = {"disabled": "disabled"}
        # form.submit(disabled=True, readonly=True)
        flash("Your data entry has been successfully loaded from the database.")

        # If past validation, during submission,
        if form.validate_on_submit() and form.update_entry.data:
            # Update.ENTRY model data
            entry_data.MRN = form.MRN.data
            entry_data.CNBPID = form.CNBPID.data
            entry_data.birth_weight = form.birth_weight.data
            entry_data.birth_date = form.birth_date.data
            entry_data.birth_time = form.birth_time.data
            entry_data.mri_date = form.mri_date.data
            entry_data.mri_reason = str(form.mri_reason.data)
            entry_data.mri_age = form.mri_age.data
            db.session.commit()

            # Notify the issue.
            flash("Your data entry has been successfully written to the database.")
        elif form.delete_entry.data:
            # Notify the issue.
            db.session.delete(entry_data)
            db.commit()
            flash(f"Entry {id_entry} was removed from the database.")

    # Post > Redirect > Get pattern.
    return render_template("entries/TEntryView.html", form=form)

app/templates/_config.html
<!--Subtemplate for Configurations. -->
<table class="table table-hover">
    <tr>
        <!--Author image. -->
        <td width="150px">
            Posted:
            <br>
            Configuration ID:
            <br>
            LORIS Username:
            <br>
        </td>

        <!--Author images and post body-->
        <td>
            {{ moment(config.timestamp).fromNow() }}:
            <br>
            <a href="{{url_for('configs.update_config', config_id=config.id)}}">Config {{config.id }}</a>
            <br>
            {{ config.LORISusername }}
            <br>

        </td>
    </tr>
</table>

app/templates/_entry.html
<!--Subtemplate for posts. -->
<table class="table table-hover">
    <tr>
        <!--Author image. -->
        <td width="150px">
            Entry ID:
            <br>
            Posted:
            <br>
            MRN:
            <br>
            CNBPID:
            <br>
            Birth Weight:
            <br>
            Birth Date:
            <br>
            Birth Time:
            <br>
            MRI Date:
            <br>
            MRI Reason:
            <br>
            MRI Age:
            <br>
        </td>

        <!--Author images and post body-->
        <td>
            <a href="{{url_for('entries.data_view', id_entry=entry.id)}}">Entry {{ entry.id }}</a>
            <br>
            {{ moment(entry.timestamp).fromNow() }} on {{ entry.timestamp }}
            <br>
            {{ entry.MRN }}
            <br>
            {{ entry.CNBPID }}
            <br>
            {{ entry.birth_weight }}
            <br>
            {{ entry.birth_date }}
            <br>
            {{ entry.birth_time }}
            <br>
            {{ entry.mri_date }}
            <br>
            {{ entry.mri_reason }}
            <br>
            {{ entry.mri_age }}
            <br>
        </td>
    </tr>
</table>

app/templates/_post.html
<!--Subtemplate for posts. -->
<table class="table table-hover">
    <tr>

        <!--Author image. -->
        <td width="70px">
            <a href="{{ url_for('main.user', username=post.author.username) }}">
                <img src="{{ post.author.avatar(70) }}" />
            </a>
        </td>

        <!--Author images and post body-->
        <td>
            <a href="{{ url_for('main.user', username=post.author.username) }}">
                {{ post.author.username }}
            </a>
             said {{ moment(post.timestamp).fromNow() }}:
            <br>
            {{ post.body }}
        </td>
    </tr>
</table>

app/templates/base.html
{% extends 'bootstrap/base.html' %}

<!--Script Block for UTC timing. add the moment.js library, without losing the base contents-->
<!--SUPER keep the base template contents-->
{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
{% endblock %}

<!--Title Block-->
{% block titile %}
    {% if titile %}{{ titile }} - DataGator {% else %}Welcome to DataGator {% endif %}
{% endblock %}

<!--Navbar Block-->
{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index')}}">DataGator</a>
            </div>


            <div class="collapse navbar-collapse" id = "bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">Home</a></li>
                    {% if current_user.is_anonymous %}
                        <li><a href="{{ url_for('main.explore') }}">Explore</a></li>
                    {% else %}
                        <li><a href="{{ url_for('entries.data_entry') }}">Add Data Entry</a> </li>
                        <li><a href="{{ url_for('entries.data_request') }}">View Data Entry</a> </li>
                        <li><a href="{{ url_for('configs.settings') }}">Configs</a> </li>
                        <li><a href="{{ url_for('configs.create_config') }}">Add Config</a> </li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_anonymous %}
                        <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                    {% else %}
                        <li><a href="{{ url_for('main.user', username=current_user.username) }}">Profile</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

<!--Content Block -->
{% block content %}
    <div class="container">
        <!--Show flashed messages here if any. -->
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-info" role="alert">{{ message }}</div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/edit_profile.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block app_content %}
    <h1>Edit Profile</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block app_content %}

    <h1>Hi, {{ current_user.username }}!</h1>


    {% if entries %}
        {% for entry in entries %}
            {% include '_entry.html' %}
        {% endfor %}
    {% endif %}    <!--Loop through all posts and include EACH using the _post subtemplate-->

    <!--Pagination Handle, recall it is from NEWEST to OLDEST-->
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span>Newer Entries
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Older Entries <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

<!--Login content page-->
{% block app_content %}

    <h1>Sign In</h1>

    <!--Login Form Block. -->
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
    <br>
    <!--Link for new user registration-->
    <p>New User? <a href="{{ url_for('register') }}">Click to Register!</a></p>
    <p>
        Forgot Your Password?
        <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
    </p>
{% endblock %}

app/templates/register.html
{%  extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{%  block app_content %}
    <h1>Register</h1>

    <div class="row">
        <div class="col-md-4">
            {{ wtf.quic_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/user.html
{% extends "base.html" %}

{% block app_content %}
    <table class="table table-hover">
        <tr>
            <!--User Content-->
            <td width="256px"><img src="{{ user.avatar(256) }}"></td>
            <td>
                <h1>User: {{ user.username }}</h1>

                <!--About me section-->
                {% if user.about_me %}
                    <p>{{ user.about_me }}</p>
                {% endif %}

                <!--Last Seen section -->
                {% if user.last_see %}
                    <p>Last seen on {{ moment(user.last_seen).format('LLL')}}</p>
                {% endif %}


                <!--Show the follower/followed count-->
                <p>{{ user.followers.count() }} followers, {{ user.followed.count() }} following.</p>

                <!--Allow edit, follow or unfollow-->
                {% if user == current_user %}
                    <p><a href="{{ url_for('main.edit_profile')}}">Edit your profile</a></p>
                {% elif not current_user.is_following(user) %}
                    <p><a href="{{ url_for('main.follow',username=user.username) }}">Follow</a></p>
                {% else %}
                    <p><a href="{{ url_for('main.unfollow',username=user.username) }}">Unfollow</a></p>
                {% endif %}
            </td>
        </tr>
    </table>

    <!--Show all posts past as an argument-->
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}

    <!--Pagination Links-->
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{%  if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> Newer posts
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Older posts <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>


{% endblock %}